build_from:
  aarch64: docker.io/mikebrady/shairport-sync:development
  armhf: docker.io/mikebrady/shairport-sync:development
  armv7: docker.io/mikebrady/shairport-sync:development
  i386: docker.io/mikebrady/shairport-sync:development
  amd64: docker.io/mikebrady/shairport-sync:development