description: Shairport Sync add-on. AirPlay 2 audio player.
name: Shairport Sync
version: "0.0.4"
slug: shairport-sync
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/charlesomer/home-assistant-addons/tree/main/shairport-sync"
host_network: true
image: ghcr.io/charlesomer/ha-addon-shairport-sync
map:
  - addon_config:r