options:
  config_file_content: |
    # Paste your shairport-sync.conf content here

schema:
  config_file_content: textarea?

description: |
  Shairport Sync add-on. AirPlay 2 audio player.

  Edit the contents of the config file directly in the UI.
name: Shairport Sync
version: "development"
slug: shairport-sync
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
url: "https://github.com/charlesomer/home-assistant-addons/tree/main/shairport-sync"
host_network: true
# audio: true
init: false
image: "docker.io/mikebrady/shairport-sync"
